repository:
  # See https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#edit for all available settings.
  # See https://github.com/apps/settings for app settings

  # A short description of the repository that will show up on GitHub
  description: An auroLabs custom element w/an experimental API. You've been warned.

  # A URL with more information about the repository
  homepage: https://auro.alaskaair.com/components/auroLabs

  # A comma-separated list of topics to set on the repository
  topics: auro-labs, design-system, custom-element, wcgen-v[genVersionDash]

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

branches:
  - name: main
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: ["blackfalcon"]
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: ["test (12.x)", "test (14.x)"]
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: auro-[name]
    cat: default
    color: fa23e4
    description:
    process: Apply to issues to identify project repo
  - name: Release
    cat: default
    color: 1c872e
    description: Defines release scope of work
    process: Apply to any issue that is the designated parent issue for a release
  - name: Issue
    cat: default
    color: 1c872e
    description: Defines issue scope of work related to release
    process: Apply to any issue that is associated to a release
  - name: duplicate
    cat: default
    color: cde6ff
    description: This Issue or Pull Request already exists
    process: When duplicate issue or pull request is discovered, please apply this label
      and add a comment so that the repo admin can address.
  - name: good first issue
    cat: default
    color: 6bb7fb
    description: Good for newcomers
    process: Apply label to issues deemed low complexity
    aliases:
    - beginner-friendly
    - beginner
    - good-starter-issue
    - good for beginner
    - Good for beginners
    - starter-issue
    - starter
  - name: help wanted
    cat: default
    process: Apply label to issues where a team resource is not immediately available and community help is requested
    color: 2492eb
    description: Extra attention is needed, this user requires assistance to complete
      the work
  - name: 'Priority: High'
    cat: default
    color: f65b7b
    description: Issues that need attention soon
  - name: released
    cat: default
    color: A9A9A9
    description: Completed work has been released
    process: 'Automated: applied once a pull request has been merged and released'
  - name: not-reviewed
    cat: default
    color: '222222'
    description: Issue has not been reviewed by Auro team member
    process: 'Automated: auto-applied with new issue, manually removed by reviewer'
  - name: 'Status: Abandoned'
    cat: default
    color: 156fad
    description: The issue or Pull Request is wontfix
    process: Apply label prior to contacting author one last time before closing issue
      or pull request
    aliases:
      - wontfix
      - invalid
  - name: 'Status: Proposal'
    cat: status
    color: fe58bc
    description: Propose new custom element or feature to existing release
    process: Apply label to issues that are proposed ideas or require discussion
    aliases:
      - idea
      - proposal
      - discussion
  - name: 'Status: Blocked'
    cat: status
    color: df0b37
    description: Immediate attention is required
    process: Apply label to issues or pull requests that blocked from progress
    aliases:
      - blocked
  - name: 'Status: Waiting on design sponsor'
    cat: status
    process: Apply label to issues where a designer's support is requested
    color: df0b37
    description: This work is waiting for a design sponsor to help define spec
    aliases:
      - blocked
  - name: 'Status: Ready to merge'
    process: Applied by author to pull requests when the work is complete and ready to merge on approval
    cat: status
    color: 29a329
    description: Owner has completed work and considers it ready to be merged
  - name: 'Status: Review Needed'
    process: Applied by author to alert the team that a review is requested
    cat: status
    color: 91be62
    description: Work is completed, user is requesting feedback
  - name: 'Status: Work In Progress'
    cat: status
    description: Issue or Pull Request work is in Progress
    color: c0e585
    process: Applied by author to alert managers and developers that work is in progress
  - name: 'Type: Bug'
    cat: type
    color: df0b37
    description: Bug or Bug fixes
    process: Author applies label type when reporting issue
    aliases:
      - bug
  - name: 'Type: CI'
    cat: type
    color: b83302
    description: Changes to CI configuration files and scripts
    process: Author applies label type when reporting issue
    aliases:
      - travis
      - ci
      - circleci
  - name: 'Type: Content or data'
    cat: type
    color: ffd200
    description: Adding or editing new content or data to the repo
    process: Author applies label type when reporting issue
    aliases:
      - enhancement
  - name: 'Type: Dependencies'
    cat: type
    color: b83302
    description: Pull requests that update a dependency file
    process: Author applies label type when reporting issue
    aliases:
      - dependencies
  - name: 'Type: Design'
    cat: type
    color: e5ad07
    description: New Design
    process: Author applies label type when reporting issue
    aliases:
      - enhancement
  - name: 'Type: Documentation'
    cat: type
    color: f26135
    description: Documentation only changes
    process: Author applies label type when reporting issue
    aliases:
      - documents
      - document
  - name: 'Type: Feature'
    cat: type
    color: e5ad07
    description: New Feature
    process: Author applies label type when reporting issue
    aliases:
      - enhancement
  - name: 'Type: Maintenance'
    cat: type
    color: b83302
    description: Repository Maintenance
    process: Author applies label type when reporting issue
    aliases:
      - greenkeeper
      - maintenance
  - name: 'Type: Question'
    cat: type
    color: b83302
    description: Further information is requested
    process: Author applies label type when reporting issue
    aliases:
      - question
  - name: 'Type: Refactoring'
    cat: type
    color: ffdb67
    description: A code change that neither fixes a bug nor adds a feature
    process: Author applies label type when reporting issue
    aliases:
      - refactor
  - name: 'Type: Testing'
    cat: type
    color: fff0cd
    description: Adding missing tests or correcting existing tests
    process: Author applies label type when reporting issue
    aliases:
      - test
      - testing
