name: General support
description: Need help with something that is not a bug or new feature request?
title: 'General support'
labels:
  - 'Type: Question'
  - not-reviewed
  - wc-generator
body:
  - type: textarea
    id: request
    attributes:
      label: General Support Request
      description: A clear and concise description of what you are interested in seeing.
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: Not obligatory, but suggest an idea of how to implement the requested update.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: Define your issue's exit criteria
      placeholder: "This issue can be closed once the error has been corrected. Any additional scope e.g. updates or refactors, should be discussed PRIOR to adding scope to this issue."
